export const COUNTRIES: { value: string; label: string }[] = [
  ["IE", "Ireland"],
  ["GB", "United Kingdom"],
  ["US", "United States"],
  ["CA", "Canada"],
  ["AU", "Australia"],
  ["DE", "Germany"],
  ["FR", "France"],
  ["ES", "Spain"],
  ["PT", "Portugal"],
  ["IT", "Italy"],
  ["NL", "Netherlands"],
  ["BE", "Belgium"],
  ["PL", "Poland"],
  ["SE", "Sweden"],
  ["CH", "Switzerland"],
  ["AE", "United Arab Emirates"],
  ["SA", "Saudi Arabia"],
  ["IN", "India"],
  ["PK", "Pakistan"],
  ["NG", "Nigeria"],
  ["ZA", "South Africa"],
  ["SG", "Singapore"],
  ["NZ", "New Zealand"],
].map(([value, label]) => ({ value: value!, label: `${label} (${value})` }));

export const TIMEZONES = [
  "Europe/Dublin",
  "Europe/London",
  "Europe/Lisbon",
  "Europe/Madrid",
  "Europe/Paris",
  "Europe/Berlin",
  "Europe/Amsterdam",
  "Europe/Warsaw",
  "Europe/Zurich",
  "Asia/Dubai",
  "Asia/Riyadh",
  "Asia/Karachi",
  "Asia/Kolkata",
  "Asia/Singapore",
  "Africa/Lagos",
  "Africa/Johannesburg",
  "America/New_York",
  "America/Chicago",
  "America/Los_Angeles",
  "America/Toronto",
  "Australia/Sydney",
  "Pacific/Auckland",
  "UTC",
].map((tz) => ({ value: tz, label: tz.replace(/_/g, " ") }));

export const CURRENCIES = [
  "EUR",
  "GBP",
  "USD",
  "AED",
  "SAR",
  "INR",
  "PKR",
  "NGN",
  "ZAR",
  "CAD",
  "AUD",
  "CHF",
  "PLN",
  "SEK",
  "SGD",
].map((c) => ({ value: c, label: c }));

export const TONES = [
  "Professional",
  "Warm",
  "Direct",
  "Expert",
  "Friendly",
  "Premium",
  "Encouraging",
];

export const PROVIDER_OPTIONS = [
  { value: "CLAUDE", label: "Claude", description: "Reasoning, drafting, coding & computer use" },
  { value: "OPENAI", label: "OpenAI", description: "Analysis, drafting and vision" },
  { value: "GROK", label: "Grok", description: "Real-time X / social intelligence" },
  { value: "LOCAL", label: "Local logic", description: "Deterministic rules — no model cost" },
] as const;
