import type {
  MeDTO,
  UserDTO,
  AgentDTO,
  ApprovalDTO,
  AuditEventDTO,
  CompanySummaryDTO,
  DashboardSummaryDTO,
  LiveSessionDTO,
  TaskDTO,
} from "@aibos/shared";

const now = new Date("2026-09-24T10:00:00Z").toISOString();

export const ept = {
  id: "c-ept",
  name: "Euro Pilot Training",
  slug: "euro-pilot-training",
  accentColor: "#2563eb",
};
export const pa = {
  id: "c-pa",
  name: "PilotsAssist",
  slug: "pilotsassist",
  accentColor: "#0d9488",
};
export const og = {
  id: "c-og",
  name: "Opportunitygrad",
  slug: "opportunitygrad",
  accentColor: "#7c3aed",
};

export function company(
  ref: typeof ept,
  extra: Partial<CompanySummaryDTO> = {},
): CompanySummaryDTO {
  return {
    ...ref,
    legalName: null,
    industry: "Aviation",
    description: null,
    website: null,
    logoUrl: null,
    primaryCountry: "IE",
    countriesServed: [],
    timezone: "Europe/Dublin",
    defaultCurrency: "EUR",
    targetAudiences: [],
    targetMarkets: [],
    productsServices: [],
    businessObjectives: [],
    primaryObjective: null,
    revenueObjective: null,
    brandPositioning: null,
    brandTone: null,
    companyRules: [],
    prohibitedClaims: [],
    competitorNotes: null,
    complianceNotes: null,
    defaultProvider: "CLAUDE",
    monthlyAiBudget: 500,
    dailyAiBudget: 25,
    concurrencyLimit: 3,
    status: "active",
    settings: {},
    origin: "dev_seed",
    createdAt: now,
    updatedAt: now,
    stats: {
      agents: 5,
      workingAgents: 2,
      openTasks: 4,
      pendingApprovals: 1,
      spendTodayUsd: 3.2,
      spendMonthUsd: 80,
    },
    ...extra,
  };
}

export function agent(extra: Partial<AgentDTO> & Pick<AgentDTO, "id" | "name">): AgentDTO {
  return {
    slug: extra.id,
    description: null,
    templateKey: "research",
    scope: "company",
    status: "sleeping",
    department: { id: "d-research", name: "Research", slug: "research" },
    reportsTo: null,
    companies: [{ ...ept, isPrimary: true }],
    primaryProvider: "CLAUDE",
    fallbackProvider: "OPENAI",
    preferredReviewerProvider: null,
    preferredModel: null,
    autonomyLevel: "observe",
    responsibilities: ["Desk research"],
    prohibitedActions: ["Spend money"],
    allowedTools: ["browser"],
    readPermissions: [],
    writePermissions: [],
    approvalRequirements: ["deep_research"],
    perTaskBudget: 2,
    dailyBudget: 10,
    maxExternalSearches: 20,
    maxRetries: 2,
    concurrencyLimit: 1,
    isTemporary: false,
    currentTask: null,
    lastActiveAt: null,
    capabilities: ["research.general", "research.web"],
    teams: [],
    workload: { active: 0, queued: 0, completedRecent: 0, capacity: 1, load: 0 },
    escalationAgent: null,
    fallbackManager: null,
    parentAgent: null,
    purpose: null,
    expiresAt: null,
    boundTaskId: null,
    maySpawnTemporary: false,
    roleVersion: null,
    preferredModelTier: "standard",
    defaultEffort: null,
    origin: "dev_seed",
    createdAt: now,
    updatedAt: now,
    ...extra,
  };
}

export const AGENTS: AgentDTO[] = [
  agent({
    id: "a1",
    name: "Group Manager",
    scope: "global",
    status: "working",
    templateKey: "company_manager",
    department: { id: "d-m", name: "Management", slug: "management" },
    companies: [],
    currentTask: { id: "t1", title: "Review today's operations", progress: 64, status: "running" },
  }),
  agent({
    id: "a2",
    name: "EPT Flight School Research",
    status: "working",
    currentTask: {
      id: "t2",
      title: "Research European EASA flight schools",
      progress: 72,
      status: "running",
    },
  }),
  agent({
    id: "a3",
    name: "EPT Grok Social Intelligence",
    primaryProvider: "GROK",
    department: { id: "d-mk", name: "Marketing", slug: "marketing" },
  }),
  agent({
    id: "a4",
    name: "Opportunitygrad Admissions",
    companies: [{ ...og, isPrimary: true }],
    department: { id: "d-s", name: "Sales", slug: "sales" },
  }),
  agent({
    id: "a5",
    name: "PilotsAssist Website / SEO",
    status: "waiting",
    companies: [{ ...pa, isPrimary: true }],
    department: { id: "d-mk", name: "Marketing", slug: "marketing" },
  }),
];

export const TASKS: TaskDTO[] = [
  {
    id: "t2",
    company: ept,
    title: "Research European EASA flight schools",
    description: null,
    type: "research",
    priority: "high",
    status: "running",
    assignedAgent: { id: "a2", name: "EPT Flight School Research" },
    createdByKind: "human",
    createdByRef: "dev-user",
    parentTaskId: null,
    rootTaskId: "t2",
    childCount: 0,
    requiredProvider: null,
    estimatedCost: 3.8,
    actualCost: 1.7,
    progress: 72,
    currentAction: "Extracting data",
    currentTool: "browser",
    requiresApproval: false,
    dueAt: null,
    startedAt: now,
    completedAt: null,
    error: null,
    resultSummary: null,
    origin: "dev_seed",
    createdAt: now,
    updatedAt: now,
  },
];

export const APPROVALS: ApprovalDTO[] = [
  {
    id: "ap1",
    company: og,
    task: null,
    agent: { id: "a6", name: "Opportunitygrad Marketing / Meta" },
    type: "ad_budget_increase",
    requestedAction: "Raise UK Masters daily budget £40 → £65",
    explanation: "CPL below target",
    riskLevel: "high",
    proposedChange: null,
    requiredPermissions: ["approval.decide", "approval.financial", "approval.high_risk"],
    viewerCanDecide: false,
    viewerMissingPermissions: ["approval.financial", "approval.high_risk"],
    decidedByUserId: null,
    beforeState: { dailyBudget: 40 },
    afterState: { dailyBudget: 65 },
    status: "pending",
    requestedAt: now,
    expiresAt: null,
    decidedBy: null,
    decisionNotes: null,
    decidedAt: null,
    origin: "dev_seed",
  },
];

export const EVENTS: AuditEventDTO[] = [
  {
    id: "e1",
    occurredAt: now,
    company: ept,
    agent: { id: "a2", name: "EPT Flight School Research" },
    taskId: "t2",
    actorType: "agent",
    actorUser: null,
    actorUserId: null,
    actorServiceId: null,
    resourceType: null,
    resourceId: null,
    action: "browser.page_read",
    tool: "browser",
    provider: null,
    description: "Extracted course data from 3 ATO websites",
    metadata: {},
    outcome: "success",
    error: null,
    origin: "dev_seed",
  },
];

export const SESSIONS: LiveSessionDTO[] = [
  {
    id: "s1",
    isMock: true,
    agent: { id: "a1", name: "Group Manager", status: "working" },
    company: null,
    task: { id: "t1", title: "Review today's operations", progress: 64 },
    surface: "application",
    currentUrl: null,
    applicationName: "AI Business OS — Operations board",
    currentAction: "Reviewing today's operations",
    currentTool: "task_router",
    lastFrameAt: now,
    control: "agent",
    timeline: [{ at: now, label: "Loaded working context", kind: "read" }],
  },
  {
    id: "s2",
    isMock: true,
    agent: { id: "a2", name: "EPT Flight School Research", status: "working" },
    company: ept,
    task: { id: "t2", title: "Research European EASA flight schools", progress: 72 },
    surface: "browser",
    currentUrl: "https://www.easa.europa.eu/en/domains/aircrew-and-medical",
    applicationName: null,
    currentAction: "Extracting fleet data",
    currentTool: "browser",
    lastFrameAt: now,
    control: "agent",
    timeline: [{ at: now, label: "Opened controlled browser profile", kind: "navigate" }],
  },
];

export const SUMMARY: DashboardSummaryDTO = {
  generatedAt: now,
  scope: null,
  companies: [company(ept), company(pa), company(og)],
  workforce: {
    sleeping: 2,
    queued: 0,
    working: 2,
    waiting: 1,
    blocked: 0,
    needs_approval: 0,
    paused: 0,
    failed: 0,
    completed: 0,
    offline: 0,
    expired: 0,
    terminated: 0,
    total: 5,
  },
  agents: AGENTS,
  tasks: TASKS,
  approvals: APPROVALS,
  activity: EVENTS,
  usage: {
    isMock: true,
    currency: "USD",
    dailyBudgetUsd: 55,
    monthlyBudgetUsd: 1100,
    todayUsd: 4.9,
    monthUsd: 402,
    liveTodayUsd: 3.7,
    liveMonthUsd: 280,
    providers: (["CLAUDE", "OPENAI", "GROK", "LOCAL"] as const).map((p, i) => ({
      provider: p,
      isMock: p !== "CLAUDE",
      todayUsd: [3.7, 0.9, 0.3, 0][i]!,
      monthUsd: [280, 85, 35, 0][i]!,
      calls: 10,
      callsToday: 2,
      billingMode: p === "CLAUDE" ? ("api" as const) : ("none" as const),
      subscriptionRunsToday: 0,
      subscriptionRunsMonth: 0,
      apiEquivalentMonthUsd: 0,
      inputTokens: 1000,
      outputTokens: 100,
      cacheReadTokens: 500,
      cacheCreationTokens: 200,
      averageCallUsd: 0.03,
      trend: Array.from({ length: 14 }, (_, d) => (i === 3 ? 0 : (d % 5) + 1)),
    })),
  },
  alerts: [],
  containsDevSeedData: true,
};

export function user(extra: Partial<UserDTO> & Pick<UserDTO, "id" | "email">): UserDTO {
  return {
    firstName: null,
    lastName: null,
    displayName: extra.email,
    avatarUrl: null,
    status: "active",
    timezone: null,
    locale: null,
    isPlatformOwner: false,
    lastLoginAt: null,
    disabledAt: null,
    createdAt: now,
    memberships: [],
    origin: "dev_seed",
    ...extra,
  };
}

const ALL_PERMS = [
  "company.view",
  "company.create",
  "user.view",
  "user.invite",
  "user.role.assign",
  "user.disable",
  "security.manage",
  "agent.view",
  "agent.permissions.manage",
  "approval.view",
  "approval.decide",
];

export const ME_OWNER: MeDTO = {
  user: user({
    id: "u-owner",
    email: "owner@aibos.example",
    displayName: "Platform Owner",
    isPlatformOwner: true,
  }),
  session: { expiresAt: now },
  isPlatformOwner: true,
  globalPermissions: ALL_PERMS,
  companyPermissions: { [ept.id]: ALL_PERMS, [pa.id]: ALL_PERMS, [og.id]: ALL_PERMS },
  accessibleCompanies: [ept, pa, og],
};

export const ME_EPT_MANAGER: MeDTO = {
  user: user({ id: "u-ept", email: "ept.manager@aibos.example", displayName: "EPT Manager" }),
  session: { expiresAt: now },
  isPlatformOwner: false,
  globalPermissions: [],
  companyPermissions: {
    [ept.id]: [
      "company.view",
      "agent.view",
      "task.view",
      "approval.view",
      "approval.decide",
      "user.view",
      "user.invite",
    ],
  },
  accessibleCompanies: [ept],
};
